### ISSUE TITLE
IllegalStateException: Can not perform this action after onSaveInstanceState

### ISSUE THREAD

**Issue by samuelhehe** [samuelhehe/androiddev_issues#8]
运行报错，提示一下错误：
java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
at android.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1109)
at android.app.FragmentManagerImpl.popBackStackImmediate(FragmentManager.java:399)
该错误出现在MainActivity中，很糟糕，问题还是在有些机型上有问题，准确的说应该是在某些系统版本上有问题
Google 搜索之后解决。

**Comment by samuelhehe** [comment]
解决方案：
网上说这是API>11 之后  在早版的 support.v4 libraries  包中的一个[bug](http://code.google.com/p/android/issues/detail?id=19917) ,具体没有深究。 
如果需要保存实例，可这样：

```
@Override
protected void onSaveInstanceState(Bundle outState) {
    outState.putString("WORKAROUND_FOR_BUG_19917_KEY", "WORKAROUND_FOR_BUG_19917_VALUE");
    super.onSaveInstanceState(outState);
}
```

**或者**可以把Commit 方法 改为 transaction.commitAllowingStateLoss();
**或者**不要调用super() ; 

```
@Override
protected void onSaveInstanceState(Bundle outState) {
    //No call for super(). Bug on API Level > 11.
}
```

网上还给了一个比较深入的blog链接：
[Fragment Transactions & Activity State Loss](http://www.androiddesignpatterns.com/2013/08/fragment-transaction-commit-state-loss.html)
我没有深入阅读，有兴趣的可以看看

查询链接：
[OnSaveInstanceState1](http://stackoverflow.com/questions/7575921/illegalstateexception-can-not-perform-this-action-after-onsaveinstancestate-h)
[OnSaveInstanceState2](http://stackoverflow.com/questions/7469082/getting-exception-illegalstateexception-can-not-perform-this-action-after-onsa)
